### ISSUE TITLE
About Wifi and Bluetooth / WifiとBluetoothについて

### ISSUE THREAD

**Issue by Yon4800** [AvaotaSBC/Avaota-A1#1]
Hello! Nice to meet you. / こんにちは！初めましてです。
I was really looking forward to this SBC coming out! thank you! / 私はこのSBCが出るのをとても楽しみにしていました！ありがとうございます！
Right away, this one seems to have Wifi and Bluetooth, but unfortunately Wifi and Bluetooth cannot be used in Japan because of the "Technical Compliance" law in Japan. / 早速なんですけど、こちらはWifi、Bluetoothがついているようですが、日本では「技適」という法律があるので日本では残念ながらWifi、Bluetoothが使えません。
Therefore, I would like you to either pass the technical standards so that it can be used in Japan, or disable Wifi and Bluetooth, or release a version that does not have Wifi and Bluetooth. / そのため、日本でも使えるように技適をとっていただくか、もしくはWifi、Bluetoothが使えないようにするか、Wifi、Bluetoothがないバージョンを出してほしいと思っています。
It may be an unreasonable request, but is it possible? / 無理な要求かもしれませんが、可能でしょうか？
I would really appreciate it if you could do it. / 本当にできればでいいのでお願いいたします
Sorry for Google translation. / Google翻訳で申し訳ないです。
I'm sorry if this isn't what I'm talking about here. Change location. / ここで話すことでなかったら申し訳ないです。場所を変えます。

**Comment by YuzukiTsuru** [comment]
もちろんです！Wi-Fiモジュールのないバージョンを購入することができます！

**Comment by Yon4800** [comment]
Thank you! / ありがとうございます！
