### ISSUE TITLE
購入先と電源端子について / About where to buy and power terminal

### ISSUE THREAD

**Issue by Yon4800** [AvaotaSBC/Avaota-A1#2]
こんにちは！
また申し訳ないです。

早速ですが一つ目の質問です。
Avaota A1の購入をそのうち検討してみようかなと考えているのですが、Aliexpressを見たところ、販売元であるDongshanPIの商品が表示できない、店舗名が表示されなくなってしまっている(shopXXXXのように表示されている)のですが、Avaota A1を購入した方のようなものをX(Twitter)で見つけましたが、まだAliexpressでは購入できないのでしょうか？

もう一つの質問は、Avaota A1の電源DCの端子(差す場所)のサイズの表記がないようですが、このサイズはどのくらいが適切でしょうか？もうすでに書いていたら申し訳ないです。

回答をお待ちしております。m(_ _)m

<br>
Hello!
I'm sorry again.

First question right away. ,
I'm thinking about purchasing Avaota A1 soon, but when I checked Aliexpress, I found that I couldn't display products from the seller, DongshanPI, and the store name was no longer displayed (like shopXXXX). However, I found someone on X (Twitter) who bought Avaota A1, but is it still not available for purchase on Aliexpress?

Another question is that there doesn't seem to be any indication of the size of the Avaota A1's power supply DC terminal (where it is plugged in), so what is the appropriate size? I apologize if this has already been written.

I look forward to your answer. m(_ _)m

<hr>

こんな感じになっています / It looks like this.
↓
![image](https://github.com/AvaotaSBC/Avaota-A1/assets/48090196/3646ce60-cc3b-4cbd-9fcd-0c7271657f7c)

**Comment by YuzukiTsuru** [comment]
現在、販売プラットフォームはまだありませんが、後で100askまたはPine64を通じて購入できます。電源には12v2AのDC電源を使用できます。

**Comment by Yon4800** [comment]
わかりました。
ありがとうございます。
後大変申し訳ございませんが、電源の端子のサイズというのは12V2Aなどの電力量(この表現で合ってるかわかりませんが)ではなくて、DCジャックの丸型端子の外径、内径のことです。
表現が悪くて申し訳ないです

**Comment by YuzukiTsuru** [comment]
![image](https://github.com/AvaotaSBC/Avaota-A1/assets/12003087/fb174738-ef40-4ae3-8f91-66f9f043a859)

**Comment by Yon4800** [comment]
ありがとうございます
