### ISSUE TITLE
GPIO 和 50FPC 排线 的针脚定义

### ISSUE THREAD

**Issue by upsangel** [AvaotaSBC/Avaota-A1#3]
你好，
感谢团队设计和生成此款开发板
请问GPIO 和 50FPC 的针脚定义 在哪里可以查到？
我只能在 https://github.com/AvaotaSBC/Avaota-A1/blob/master/hardware/v1.4/01_SCH/SCH_Avaota%20Pi%20A_2024-05-20.pdf 倒数第二页猜到这是针脚的定义，可以给出更加清晰的指引吗？就像树莓派、香橙派之类都会列出每个针脚的顺序和调试。
现阶段的目标是想适配合适的触摸屏，
谢谢！

**Comment by SamulKyull** [comment]
![image](https://github.com/user-attachments/assets/c080d561-7dd5-42e2-81a3-f01bf098f399)

**Comment by upsangel** [comment]
Thank you!
