### ISSUE TITLE
Looking for Manufacturing Details

### ISSUE THREAD

**Issue by aldwinhermanudin** [AvaotaSBC/Avaota-A1#4]
Hi,

First of all, thank you for creating an open-source SBC design! This is really awesome, and I will definitely helps others a lot!
I'm currently trying to manufacture the SBC myself so I can start tinkering with the design. but I have couple of questions below,

- There are missing `Supplier Part` for some of the discrete components, like the capacitors. Are there a required specifications for those? for example, can I choose any ​`tolerance`, and `​temperature coefficient` for the capacitor?
- Where can I find the stack-up information for the board, such as `layer thickness` and layer `Dielectric constant (Dk)` ?

Thank you!

**Comment by SamulKyull** [comment]
- Supplier Part
  - Some part we got from Taobao.com and really don't know his part number,
  - The 0201 capacitor requires 6.3v withstand voltage, 0402 requires 10v, and 0603 requires 25v
  - Resistors please use 1% accuracy
- stack-up information:

![image](https://github.com/user-attachments/assets/f41e8570-291c-4f9e-a5f4-d977d35ab273)

**Comment by aldwinhermanudin** [comment]
Thank you!
