### ISSUE TITLE
Android - Root is not enabled?

### ISSUE THREAD

**Issue by upsangel** [AvaotaSBC/Avaota-A1#5]
Flashed with t527_android13_avaota_a1_uart0_eng.zip	, adb with USB no problem, network adb can be enabled no problem. 
But ROOT is not enabled in this image? Is there a root image with root, or how to enable root in t527_android13_avaota_a1_uart0_eng ?
Thank you!

**Comment by YuzukiTsuru** [comment]
Yes

**Comment by upsangel** [comment]
> Yes

Thank you for your reply.

I saw on your official page: https://docs.avaota.fun/android/build/build

t527_avaota_a1_arm64-eng：开发版，开放串口控制台，**ROOT等**。内核适配时使用。

But I flashed the t527_android13_avaota_a1_uart0_eng.zip (https://pan.baidu.com/s/1HMWV-rDZNWTkFrdo7tcsWg?pwd=avat) it has no root. 

Would you mind sharing the link for an img with 开发版，开放串口控制台，**ROOT等** available to download?

Thank you!

**Comment by SamulKyull** [comment]
This ROOT is only adb and UART shell can use, if APP want to use ROOT, you need modify some code from SDK

https://docs.avaota.fun/android/develop/root

**Comment by thanhtantran** [comment]
I don't have baidu account to download android, can anyone upload to google drive  please?

**Comment by kiramint** [comment]
> I don't have baidu account to download android, can anyone upload to google drive please?

# VERSION V1.0 2024-05-12

https://docs.avaota.fun/android/intro/os-download/

* Google Drive:

https://drive.google.com/drive/folders/1YeETOa5ot2Mqtaewnu21enkNiNQ0x86e?usp=sharing

> You should unzip before calculating the md5

The sdk is too big to upload (60GB) sorry~
